// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.github.crbanman.mattermost-plugin-tableflipdown",
	Version: "1.2",
}
